services:
  app:
    image: python:3.11-alpine
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "pip install --no-cache-dir --disable-pip-version-check pyTelegramBotAPI requests && python main.py"
    restart: unless-stopped
